### ISSUE TITLE
64-bit mac version

### ISSUE THREAD

**Issue by dzwiener** [StanWarford/pep8#2]
Currently Apple is phasing out all 32-bit programs and in ~1 year they will no longer allow any 32 bit applications to run on their platform. I believe pep8 is 32-bit and would need to be updated.

**Comment by StanWarford** [comment]
Yes, our development version is 64-bit, and we will update eventually.

**Comment by Matthew-McRaven** [comment]
This has been fixed with a release  based on #6. The binaries are currently available over on the release page, but will be posted to the book website soon.
